In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

#Internal ipython tool for setting figure size
from IPython.core.pylabtools import figsize

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print(a[0,0])
print(a[0,:])
print(a[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 2 3]
[1 4 7]
